Repository wp-cli/php-cli-tools, pull requests merged in 2023-11, with the labels that each got.

#141 Fix type hinting for prompt function
  lib/cli/Streams.php
  lib/cli/cli.php
Labels: enhancement, scope:documentation

#167 Remove inexistent `post-install-cmd`
  composer.json
Labels: scope:testing

#168 Use class instead of static variables for the speed measurement
  lib/cli/Notify.php
Labels: bug, scope:progress
